import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, ArrowUpRight } from "lucide-react";
import { ClayIcon } from "@/components/StudioIcon";
export const metadata = { title: "About the studio", alternates: { canonical: "/en/about", languages: { ko: "/about", en: "/en/about" } } };
export default function EnglishAbout() {
  return <div className="studio-subpage about-page">
    <header className="subpage-hero"><div><p className="eyebrow">A SMALL STUDIO / OUR STORY</p><h1>A place to learn,<br /><span>play, and take a break.</span></h1><p className="subpage-lead">Letpang is an indie studio making mobile games<br />and apps for the little moments in your day.</p><Link className="button button-dark" href="/en/#games">Meet our games<span className="button-arrow"><ArrowUpRight size={20} aria-hidden="true" /></span></Link></div><div className="about-hero-art"><Image src="/art/letpang-world-v1.webp" alt="The little play world of Letpang Studio" width={1536} height={1024} sizes="(max-width: 760px) 100vw, 550px" priority /></div></header>
    <section className="about-intro"><p className="eyebrow">WHAT WE MAKE</p><h2>Different kinds of fun.<br />The same care within.</h2><div><p>Hanja Pop brings the satisfaction of learning one character at a time. Wakppop offers a squishy, sensory break at your fingertips.</p><p>Color Sense turns color puzzles into a world of cats to find and nurture. Hangul Street takes you on a trip through Seoul while you learn Korean.</p><p>Each game is different, but they share a simple wish: to make starting something new feel easy and enjoyable.</p></div></section>
    <section><div className="subsection-heading"><p className="eyebrow">THE WAY WE MAKE</p><h2>What matters to us</h2></div><div className="about-values"><article><ClayIcon kind="play" /><h3>An easy first step</h3><p>We refine the controls and flow so you can see what to do, even on your first visit.</p></article><article><ClayIcon kind="book" /><h3>Learning, little by little</h3><p>We add quizzes and play to the process of discovering a character or a word, making small achievements feel good.</p></article><article><ClayIcon kind="heart" /><h3>Moments worth revisiting</h3><p>We care about colors, sounds, and the feel of each interaction, so a short session can brighten your day.</p></article></div></section>
    <section className="about-invitation"><div><p className="eyebrow">KEEP IN TOUCH</p><h2>Be part of the next story.</h2><p>Share your game feedback through Support,<br />or email us with something you’d like to create together.</p></div><div><Link className="button button-dark" href="/en/support">Support<span className="button-arrow"><ArrowUpRight size={20} aria-hidden="true" /></span></Link><a className="text-link" href="mailto:biz@letpang.com">Collaborate with us<ArrowUpRight size={17} aria-hidden="true" /></a></div></section>
    <Link className="text-link" href="/en"><ArrowLeft size={16} aria-hidden="true" />Back to home</Link>
  </div>;
}
