import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, ArrowUpRight, BriefcaseBusiness, Clock3, Image as ImageIcon, Mail, MessageCircle, MonitorSmartphone } from "lucide-react";
import { englishGames } from "@/lib/english-games";
import { SITE } from "@/lib/site";
export const metadata = { title: "Support", alternates: { canonical: "/en/support", languages: { ko: "/support", en: "/en/support" } } };
function supportLink(name: string) { return `mailto:${SITE.email}?subject=${encodeURIComponent(`[${name}] Support`)}&body=${encodeURIComponent(`Game: ${name}\nDevice model:\nOS / app version:\n\nWhat happened?\n\n`)}`; }
export default function EnglishSupport() {
  return <div className="studio-subpage support-page">
    <header className="subpage-hero"><div><p className="eyebrow">HERE TO HELP / SUPPORT</p><h1>A question?<br /><span>A little trouble?</span></h1><p className="subpage-lead">If something gets in the way of your play, let us know.<br />We’ll take a look at what happened.</p><a className="button button-dark" href={`mailto:${SITE.email}`}><Mail size={20} aria-hidden="true" />Email support<span className="button-arrow"><ArrowUpRight size={20} aria-hidden="true" /></span></a><p className="response-note"><Clock3 size={15} aria-hidden="true" />We usually reply within 2–3 business days.</p></div><div className="support-hero-art" aria-hidden="true"><Image src="/art/studio-letter-v1.webp" alt="" width={960} height={640} sizes="(max-width: 760px) 80vw, 420px" priority /></div></header>
    <section><div className="subsection-heading"><p className="eyebrow">01 / CHOOSE YOUR GAME</p><h2>Which game is it about?</h2><p>Choose a game to open an email with its name and a few helpful prompts.</p></div><div className="support-game-grid">{englishGames.map(game => <a className="support-game" href={supportLink(game.title)} key={game.id}><Image src={game.iconUrl} alt="" width={64} height={64} /><div><h3>{game.title}</h3><span>Contact us about this game</span></div><ArrowUpRight size={18} aria-hidden="true" /></a>)}</div></section>
    <section className="support-prep"><div><p className="eyebrow">02 / A FEW HELPFUL DETAILS</p><h2>Help us understand<br />what happened.</h2><p>A short description is enough.<br />Tell us where you ran into the problem.</p></div><div className="support-checklist"><div><span className="prep-icon"><MonitorSmartphone aria-hidden="true" /></span><div><h3>Your setup</h3><p>Device model, iOS or Android version, and app version</p></div></div><div><span className="prep-icon"><MessageCircle aria-hidden="true" /></span><div><h3>The moment it happened</h3><p>Which screen you were on, what you did, and what went wrong</p></div></div><div><span className="prep-icon"><ImageIcon aria-hidden="true" /></span><div><h3>A picture, if you have one</h3><p>A screenshot or short video can help us understand the situation.</p></div></div></div></section>
    <section className="support-contact-grid" aria-label="Contact details"><a href={`mailto:${SITE.email}`} className="support-contact"><Mail aria-hidden="true" /><div><h2>Game support</h2><p>Bug reports, questions, and feedback</p><strong>{SITE.email}</strong></div><ArrowUpRight size={20} aria-hidden="true" /></a><a href="mailto:biz@letpang.com" className="support-contact"><BriefcaseBusiness aria-hidden="true" /><div><h2>Business & collaboration</h2><p>Tell us what you’d like to make together</p><strong>biz@letpang.com</strong></div><ArrowUpRight size={20} aria-hidden="true" /></a></section>
    <section className="support-faq"><p className="eyebrow">03 / QUICK ANSWERS</p><h2>A few things you might wonder</h2><details><summary>Where can I download the games?</summary><p>Visit <Link href="/en/#games">our games</Link> and choose the App Store or Google Play button.</p></details><details><summary>When will I hear back?</summary><p>We usually reply within 2–3 business days. Including the issue and your device details helps us investigate.</p></details><details><summary>Can I send feedback instead of a bug report?</summary><p>Of course. Tell us what you enjoyed, what could be better, or what you’d love to see next.</p></details></section>
    <Link className="text-link" href="/en"><ArrowLeft size={16} aria-hidden="true" />Back to home</Link>
  </div>;
}
