import Image from "next/image";
import Link from "next/link";
import { FaApple, FaGooglePlay } from "react-icons/fa6";
import { ArrowLeft, ShieldCheck } from "lucide-react";
import { SITE } from "@/lib/site";
const game = SITE.games.hanja;
export const metadata = { title: "Hanja Pop — Learn Hanja", description: game.description, alternates: { canonical: "/en/games/hanja-explorer", languages: { ko: game.path, en: "/en/games/hanja-explorer" } } };
export default function EnglishHanja() {
  return <div className="page-container"><header className="page-header"><Image src={game.iconUrl} alt="Hanja Pop icon" width={96} height={96} /><h1 className="page-title">Hanja Pop</h1><p className="page-subtitle">{game.description}</p></header><section className="content-card"><h2>Learn a little every day</h2><p>Build a daily Hanja habit with graded lessons, character cards, stroke-order practice, word quizzes, and review games. Prepare step by step for grades 8 through 6.</p></section><div className="features" style={{ marginBottom: 40 }}><article className="feature-card"><h3>A five-minute routine</h3><p className="feature-desc">Learn today’s characters, then review with quizzes and mini-games.</p></article><article className="feature-card"><h3>Graded practice</h3><p className="feature-desc">Work through lessons and practice tests for grades 8 through 6.</p></article><article className="feature-card"><h3>Write and review</h3><p className="feature-desc">Practice stroke order and revisit words you found tricky.</p></article></div><section className="contact-card"><h2>Get Hanja Pop</h2><p>Available on iOS and Android.</p><div className="hero-buttons"><a href={game.appStoreUrl} className="btn" target="_blank" rel="noopener noreferrer"><FaApple aria-hidden="true" />App Store</a><a href={game.playStoreUrl} className="btn" target="_blank" rel="noopener noreferrer"><FaGooglePlay aria-hidden="true" />Google Play</a></div></section><div className="hero-buttons" style={{ marginTop: 35 }}><Link href="/en/games/hanja-explorer/privacy" className="back-link"><ShieldCheck size={16} aria-hidden="true" />Privacy policy</Link><Link href="/en" className="back-link"><ArrowLeft size={16} aria-hidden="true" />Back to home</Link></div></div>;
}
