// lib/site.ts
export const SITE = {
  name: "Letpang Studio",
  description: "감성적인 캐주얼 모바일 게임을 만드는 인디 게임 스튜디오",
  email: "hello@letpang.com",
  games: {
    hanja: {
      id: "hanja-explorer",
      title: "Hanja Pop",
      titleKr: "한자팝",
      description: "Build a daily Hanja routine with graded lessons, writing practice, quizzes, and review games.",
      descriptionKr: "하루 5분, 급수별 한자 학습부터 획순 쓰기·퀴즈·미니게임 복습까지",
      path: "/games/hanja-explorer",
      privacyPath: "/games/hanja-explorer/privacy",
      playStoreUrl: "https://play.google.com/store/apps/details?id=com.soujinne.hanjaexplorer",
      appStoreUrl: "https://apps.apple.com/kr/app/id6762037956",
      iconUrl: "/icons/hanja-pop.jpg",
      isNew: true,
    },
    wakppop: {
      id: "wakppop",
      title: "Wakppop",
      titleKr: "왁뿌팝",
      description: "Relax with squishy ASMR toys, slime, crunchy balls, and clickable keycaps.",
      descriptionKr: "왁뿌볼·슬라임·키캡·스퀴시를 누르고 늘리며 즐기는 말랑한 ASMR 놀이터",
      playStoreUrl: "https://play.google.com/store/apps/details?id=com.dh.pastelothello",
      appStoreUrl: "https://apps.apple.com/kr/app/id6755481318",
      iconUrl: "/icons/wakppop.jpg",
    },
    colorSense: {
      id: "color-sense",
      title: "Color Sense",
      titleKr: "Color Sense: 고양이 색 찾기",
      description: "Find the differently colored cat, collect new cats, and decorate their room.",
      descriptionKr: "다른 색의 고양이를 찾는 컬러 퍼즐! 고양이를 수집하고 성장시키며 나만의 방을 꾸며보세요.",
      playStoreUrl: "https://play.google.com/store/apps/details?id=com.dh.chroma",
      appStoreUrl: "https://apps.apple.com/kr/app/id6756197799",
      iconUrl: "/icons/color-sense-cat.jpg",
    },
    hangulStreet: {
      id: "hangul-street",
      title: "Hangul Street: Learn Korean",
      titleKr: "Hangul Street: Learn Korean",
      description: "Learn Korean words through a cute virtual trip around Seoul.",
      descriptionKr: "귀여운 서울 여행 게임으로 한국어 단어를 배워요.",
      playStoreUrl: "https://play.google.com/store/apps/details?id=com.dh.hangulstreet",
      appStoreUrl: "https://apps.apple.com/kr/app/id6793157518",
      iconUrl: "/icons/hangul-street.jpg",
    },
    hangulPop: {
      id: "hangulpop",
      title: "Hangul Pop",
      titleKr: "한글팝",
      description: "Learn useful Korean through short, playable everyday conversations.",
      descriptionKr: "짧고 실용적인 일상 대화를 풀며 한국어를 배우는 학습 게임",
      playUrl: "https://hangulpop.letpang.com",
      comingSoon: true,
    },
  }
};
