import Image from "next/image";
import Link from "next/link";
import { Mail } from "lucide-react";
import GameCard from "@/components/GameCard";
import { ArrowIcon, ClayIcon } from "@/components/StudioIcon";
import { englishGames } from "@/lib/english-games";
import { SITE } from "@/lib/site";
export const metadata = { alternates: { canonical: "/en", languages: { ko: "/", en: "/en" } } };

export default function EnglishHome() {
  return <div className="studio-home">
    <section className="studio-hero" aria-labelledby="hero-heading"><div className="hero-copy"><p className="eyebrow"><span className="status-dot" />SMALL STUDIO. HAPPY LITTLE MOMENTS.</p><h1 id="hero-heading">A little more<br /><span className="hero-highlight">joy in your day.</span></h1><p className="hero-description">Learn a new character. Find a curious cat.<br />Take a wonderfully squishy break.<br />Make today a little brighter with Letpang.</p><div className="hero-actions"><a className="button button-dark" href="#games"><ClayIcon kind="play" />Explore our games<span className="button-arrow"><ArrowIcon diagonal /></span></a><Link className="text-link story-link" href="/en/about">Our story<span className="link-arrow"><ArrowIcon /></span></Link></div><div className="hero-footnote"><span className="tiny-platform">iOS + Android</span><span>Little worlds in your hands</span></div></div><figure className="hero-world"><Image src="/art/letpang-world-v1.webp" alt="Letpang characters, a rainbow squishy ball, and a miniature Seoul" width={1536} height={1024} sizes="(max-width: 760px) 100vw, 60vw" priority /><figcaption><span className="status-dot" />FOUR LITTLE WORLDS, ONE HAPPY PLACE.</figcaption></figure></section>
    <div className="studio-strip" aria-label="What we make"><div className="strip-item"><ClayIcon kind="book" /><div><span>LEARN A LITTLE</span><p>A little discovery</p></div></div><div className="strip-item"><ClayIcon kind="play" /><div><span>PLAY A LOT</span><p>A lot of play</p></div></div><div className="strip-item"><ClayIcon kind="heart" /><div><span>FEEL GOOD</span><p>A happy little break</p></div></div></div>
    <section className="portfolio-section" id="games" aria-labelledby="games-heading"><div className="section-heading"><div><p className="eyebrow">01 / OUR LITTLE WORLDS</p><h2 id="games-heading">Find your kind of fun.<br /><span>There’s more than one.</span></h2></div><p className="section-note">For days of discovery and moments of rest.<br />Pick a game to match your mood.</p></div><div className="portfolio-grid">{englishGames.map(game => <GameCard key={game.id} game={game} locale="en" />)}</div></section>
    <section className="next-world" aria-labelledby="next-heading"><div className="next-illustration" aria-hidden="true"><Image src="/art/hangul-world-v1.webp" alt="" width={1536} height={1024} sizes="(max-width: 760px) 70vw, 280px" /></div><div className="next-copy"><p className="eyebrow">NEXT LITTLE WORLD / COMING SOON</p><h2 id="next-heading">Next up: Hangul Pop.</h2><p>Learn practical Korean through short everyday conversations.<br />We’re getting its first story ready for you.</p></div><span className="coming-label"><span className="status-dot" />Coming soon</span></section>
    <section className="studio-story" aria-labelledby="story-heading"><div className="story-intro"><p className="eyebrow">02 / THE WAY WE MAKE</p><h2 id="story-heading">A small studio.<br />A lot of heart.</h2><Link href="/en/about" className="text-link">Meet Letpang<ArrowIcon diagonal /></Link></div><div className="story-values"><div><span className="value-number">01</span><h3>Easy to get into</h3><p>A clear first step, a simple interaction.<br />Jump in and discover as you go.</p></div><div><span className="value-number">02</span><h3>Learning feels like play</h3><p>One character, one word, one little challenge.<br />Small achievements add up.</p></div><div><span className="value-number">03</span><h3>Care in the little things</h3><p>A color, a sound, a response to your touch.<br />We craft moments you’ll want to revisit.</p></div></div></section>
    <section className="hello-section" aria-labelledby="hello-heading"><div className="hello-copy"><p className="eyebrow">GOOD THINGS START WITH A HELLO.</p><h2 id="hello-heading">Good things happen<br />when we create together.</h2><p>A thought about our games, a new idea, a collaboration.<br />We’d love to hear your story.</p><a className="button button-cream" href={`mailto:${SITE.email}`}><Mail className="mail-icon" aria-hidden="true" />{SITE.email}<span className="button-arrow"><ArrowIcon diagonal /></span></a></div><div className="hello-art" aria-hidden="true"><Image src="/art/studio-letter-v1.webp" alt="" width={1536} height={1024} sizes="(max-width: 760px) 80vw, 480px" /><span className="hello-note">A LITTLE HELLO.<br />A WHOLE LOT OF POSSIBILITIES.</span></div></section>
  </div>;
}
